"""The supplied PS26145 dataset field is a generator specification, not a download list."""
from __future__ import annotations

import json
from pathlib import Path

from engine.models.tier1 import sha256_file

GENERATORS = (
    ("iperf3", ["benign"]), ("Ostinato", ["benign"]), ("TRex", ["benign"]),
    ("hping3", ["syn_flood", "udp_reflection"]), ("Slowloris", ["slowloris"]),
    ("dnscat2", ["dns_tunnel"]), ("iodine", ["dns_tunnel"]),
    ("published DGA / DGArchive", ["dga_burst"]), ("sandboxed C2 emulator", ["beacon_jitter"]),
)


def problem_statement_inventory(root: Path) -> dict:
    reports = []
    for path in sorted((root / "data/lab-runs").glob("*/report.json"))[:100]:
        try:
            report = json.loads(path.read_text())
            expected = {"iperf.json", "intervals.flows.csv"}
            if set(report.get("hashes", {})) != expected:
                raise ValueError("Lab report must fingerprint both raw counters and normalized flows")
            report["integrity_ok"] = all(sha256_file(str(path.parent / name)) == report["hashes"][name] for name in expected)
            reports.append(report)
        except (OSError, ValueError, KeyError):
            reports.append({"id": path.parent.name, "integrity_ok": False, "generator": "unknown"})
    return {"id": "26145", "downloadable_datasets_provided": False,
        "note": "The supplied dataset field names generators. Bundled PCAPs emulate them; they were synthesized with dpkt, not generated by these tools.",
        "generators": [{"tool": name, "bundled_scenarios": ids,
            "status": "verified local counters; no PCAP" if name == "iperf3" and any(
                r.get("generator") == "iperf3" and r.get("integrity_ok") for r in reports) else "synthetic emulation only; real tool data missing"}
            for name, ids in GENERATORS], "lab_runs": reports}
