"""Capture exactly our own small UDP loopback exchange. Never captures a general interface."""
from __future__ import annotations

import json
from pathlib import Path
import platform
import shutil
import socket
import subprocess
import time
import uuid

from engine.models.tier1 import sha256_file
from engine.pipeline import Engine
from engine.sources.pcap_source import PcapSource

ROOT = Path(__file__).resolve().parents[1]


def analyse(path: Path) -> dict:
    engine = Engine()
    counts: dict[str, int] = {}
    source = PcapSource(str(path))
    for packet in source:
        for alert in engine.feed(packet) + engine.tick(packet.ts_ns):
            counts[alert.threat_class] = counts.get(alert.threat_class, 0) + 1
    engine.sweep()
    if not engine.packets:
        raise RuntimeError("Capture contained no decodable IP packets")
    return {"file": path.name, "provenance": "real-local-loopback", "sha256": sha256_file(str(path)),
            "bytes": path.stat().st_size, "packets": engine.packets,
            "detections": counts, "source_stats": source.stats(),
            "coverage": engine.stats()["coverage_counts"],
            "limitations": "Only a small benign exchange generated by this test. Not representative network traffic or attack validation."}


def capture() -> dict:
    binary = shutil.which("tcpdump")
    if binary is None:
        raise RuntimeError("tcpdump is required")
    folder = ROOT / "data/captures"
    folder.mkdir(mode=0o700, parents=True, exist_ok=True)
    path = folder / ("loopback-" + uuid.uuid4().hex + ".pcap")
    interface = "lo0" if platform.system() == "Darwin" else "lo"
    # Both ports are held by this process; the filter excludes unrelated loopback traffic.
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as receiver, socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sender:
        receiver.bind(("127.0.0.1", 0))
        sender.bind(("127.0.0.1", 0))
        receiver.settimeout(1)
        destination, origin = receiver.getsockname()[1], sender.getsockname()[1]
        packet_filter = f"udp and src host 127.0.0.1 and dst host 127.0.0.1 and src port {origin} and dst port {destination}"
        command = [binary, "-i", interface, "-n", "-U", "-s", "96", "-c", "8", "-w", str(path), packet_filter]
        process = subprocess.Popen(command, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)
        try:
            time.sleep(0.5)
            if process.poll() is not None:
                raise RuntimeError(process.communicate()[1].strip())
            for _ in range(8):
                sender.sendto(b"SIH local capture validation", ("127.0.0.1", destination))
                receiver.recvfrom(128)
                time.sleep(0.05)
            _, stderr = process.communicate(timeout=5)
            if process.returncode:
                raise RuntimeError(stderr.strip())
        finally:
            if process.poll() is None:
                process.terminate()
                try:
                    process.communicate(timeout=2)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.communicate()
    path.chmod(0o600)
    report = analyse(path)
    (path.with_suffix(".report.json")).write_text(json.dumps(report, indent=2) + "\n")
    return report


if __name__ == "__main__":
    try:
        print(json.dumps(capture(), indent=2))
    except (OSError, RuntimeError, subprocess.TimeoutExpired) as exc:
        raise SystemExit(f"Capture unavailable: {exc}")
